name: CNN-COVID-19-classification-using-chest-CT-scan
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.2.2
  - notebook=6.0.3
  - numpy=1.18.5
  - pandas=1.0.5
  - python=3.7.7
  - scikit-learn=0.23.1
  - seaborn=0.10.1
  - scipy=1.4.1
  - pip:
    - tensorflow==2.3.0

