name: deep-learning-from-scratch-pytorch
channels:
- conda-forge
- defaults
- anaconda
dependencies:
- python=3.6
- jupyter=1.0.0
- matplotlib=3.1.1
- pandas=0.25.1
- scipy=1.3.1
- scikit-learn=0.23
- seaborn=0.9.0
- pytorch=1.4.0
